### ISSUE TITLE
Feature suggestion: allow user to save favorite locations (city/country)

### ISSUE THREAD

**Issue by zaneselvans** [AlexPoilrouge/NordVPN-connect#6]
Thank you for making a great extension! I've wanted exactly this thing for like a year.

One suggestion -- you allow folks to save a favorite server by adding whatever the current server is, but I think it might also be useful to allow folks to choose a particular country or city to save as favorites, since I think nordvpn does some load balancing to ensure you are connecting to the least busy of the servers that matches your request (of protocol, location, services, etc.). Which means hard-coding a particular server as a favorite might later mean connecting to a busy server, when really all you want to specify is a given jurisdiction.

It seems like this ought to be pretty easy to set up, since you can give the CLI a country or city as an argument, and it will connect to a server in that location.

Anyway, thank you again for making NordVPN more user friendly on Linux.

**Comment by zaneselvans** [comment]
(also, the extension seems to work great on Ubuntu 19.04, with gnome-shell 3.32.1, and nordvpn 3.3.0-1)

**Comment by AlexPoilrouge** [comment]
Hello. Thank you, glad you like this extension. 😀

I do get your point about how setting a particular server as favourite might not always be ideal.
Although, I don't really understand the utility of setting a favourite location, since picking the location you want to connect to was the very first feature of this extension.
That being said, I am aware that choosing a particular city to connect to is still a missing feature, on which I do intend to work on.

**Comment by zaneselvans** [comment]
One can choose the location, but there are a lot of countries, and I only need to use a couple of them on a regular basis, so it would be nice to be able to have say "United States", "Costa Rica", and "Switzerland" as favorites that are immediately visible (as it the case now with individual favorite servers), rather than having to scroll through a couple of screens in the big list.

**Comment by AlexPoilrouge** [comment]
I understand the issue.

I'll think about a solution when I can.

**Comment by AlexPoilrouge** [comment]
Hello back.

So, I thought about the issue, so here's what I have done:
- A 'recent locations list is not available on top the 'server favourite'.
- This list is actually a queue, where each time you connect (through the extension) to a location, the location is put on top of the queue.
- The queue has a limitation of 4 items, but that limit can be changed in the extension settings page.
- Any location in this queue can be 'pinned', so that it will remain of top of the queue.

This change is available with the latest commit on the master branch.

I believe that this should be an acceptable answer to your point, hopefully you'd agree to some degree.

**Comment by zaneselvans** [comment]
Yes, that sounds great. Thanks for the update! Will the change propagate into the gnome-shell updates somehow automatically, or does it have to be updated manually?

**Comment by AlexPoilrouge** [comment]
I'm not sure what you refer to specifically…

This update will be available through the usual means of the gnome-shell extensions updates systems. I don't know whether you use a program like gnome-tweaks, or if you go through the [gnome extension website](https://extensions.gnome.org), but it should be as every other extensions.

There's is however a varying delay for the update, as every extension and extension update goes through a code review process. It has been submitter, so hopefully in a few days.
